/*
 * generated by Xtext
 */
package org.xtext.example.mydsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends org.xtext.example.mydsl.AbstractMyDslRuntimeModule {
	public Class<? extends org.eclipse.xtext.generator.IGenerator> bindIGenerator() {
		return org.xtext.example.mydsl.generator.MyDslGenerator.class;
	}
}
